// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSfpioU8frOX5m5VqNWygd_Wg7MvbW8dA',
    appId: '1:544328320313:web:2e30736e0a7ff4faed14e8',
    messagingSenderId: '544328320313',
    projectId: 'phoneto-9c82c',
    authDomain: 'phoneto-9c82c.firebaseapp.com',
    storageBucket: 'phoneto-9c82c.appspot.com',
    measurementId: 'G-0LKJGGJYKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV_kKVqCQwzNVlSeiBF88nJLGEVCTAtjk',
    appId: '1:544328320313:android:4e61ec6880e3f103ed14e8',
    messagingSenderId: '544328320313',
    projectId: 'phoneto-9c82c',
    storageBucket: 'phoneto-9c82c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeVrlh0xwyS_CRNiodq8B5k9AuFqNicLk',
    appId: '1:544328320313:ios:aa747fc9b2ef5de1ed14e8',
    messagingSenderId: '544328320313',
    projectId: 'phoneto-9c82c',
    storageBucket: 'phoneto-9c82c.appspot.com',
    iosClientId:
        '544328320313-1vbnajouobd8q3qktj52ajs2btscp0fs.apps.googleusercontent.com',
    iosBundleId: 'com.trithon.phoneto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeVrlh0xwyS_CRNiodq8B5k9AuFqNicLk',
    appId: '1:544328320313:ios:aa747fc9b2ef5de1ed14e8',
    messagingSenderId: '544328320313',
    projectId: 'phoneto-9c82c',
    storageBucket: 'phoneto-9c82c.appspot.com',
    iosClientId:
        '544328320313-1vbnajouobd8q3qktj52ajs2btscp0fs.apps.googleusercontent.com',
    iosBundleId: 'com.trithon.phoneto',
  );
}
